# provisioning/datasources/tinybird.yaml
apiVersion: 1

datasources:
  - name: Tinybird Electric Grid Datasources
    type: yesoreyeram-infinity-datasource
    access: proxy
    isDefault: true

    jsonData:
      auth_method: bearerToken
      allowedHosts:
        - https://api.tinybird.co
      customHealthCheckEnabled: true
      customHealthCheckUrl: https://api.tinybird.co/v0/pipes/generation_ep.json
      oauthPassThru: false

    secureJsonData:
      # authenticationMethod: bearerToken
      bearerToken: ${TINYBIRD_TOKEN}

  - name: Tinybird via ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    isDefault: false
    url: https://api.tinybird.co
    basicAuth: false

    jsonData:
      server: api.tinybird.co
      port: 443
      protocol: http
      secure: true
      defaultDatabase: default
      httpMode: 'POST'
      path: /v0/sql
      httpHeaders:
        - name: Authorization
          value: Bearer ${TINYBIRD_TOKEN}
          secure: true

